# Generated by Django 4.0.3 on 2022-03-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='health_department',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='police_department',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_location',
            field=models.CharField(max_length=255),
        ),
    ]
